### ISSUE TITLE
Fix TODOs in tests or remove incomplete tests

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#100]
example: it's not obvious what `test_TestDelegateConsistentSnapshotDisabled()` gives us: it seems to be lacking both a description of what it is testing and the HTTP request assertions that the upstream go-tuf test has.

Let's go through the tests with TODOs and FIXMEs and either complete them or remove them as incomplete.

**Comment by AdamKorcz** [comment]
Removing `test_TestDelegateConsistentSnapshotDisabled` in https://github.com/theupdateframework/tuf-conformance/pull/103

**Comment by jku** [comment]
Filed #107 as a specific sub-issue

**Comment by AdamKorcz** [comment]
I believe all TODOs in tests are resolved.
