### ISSUE TITLE
GH Action does not work in a matrix job

### ISSUE THREAD

**Issue by segiddins** [theupdateframework/tuf-conformance#110]
See e.g. https://github.com/sigstore/sigstore-ruby/actions/runs/10254251941/job/28368619654?pr=69

This fails because `Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run`, because the output name is based only on the entry point name

**Comment by jku** [comment]
Hmm, it's not immediately obvious how to automatically choose a good name...
* I guess we could add an optional input to use as artifact name
* or we could add an input that could be used to enable/disable artifact creation -- it is debugging data after all, not needed for the test itself

**Comment by segiddins** [comment]
why not have it include a UUID, and make the name an output of the action? alternatively, disabling also makes sense

**Comment by jku** [comment]
Yeah something like that would work...

Maybe disabling is fine: the repository content should be essentially the same for each run anyway (only keys and signatures differ)
