### ISSUE TITLE
RepositorySimulator._compute_hashes_and_length is broken

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#128]
EDIT: Every test that uses `RepositorySimulator._compute_hashes_and_length = True` is currently broken because :
* the simulator signs at request time
* ecdsa signatures are not deterministic
* hashes/length calculation is done over the whole file (so it includes these changing signatures)

This should get fixed if any option of #130 is implemented
 
Original report was :

---

test_snapshot_rollback_with_local_snapshot_hash_mismatch() does not seem right:
 * the metadata changes in the test seem valid, yet client fails refresh
 * test claims in comments to do a  target version rollback but does not?
 * client actually fails because length and hash are incorrect?
 
I can't quite see what the issue is. 

We should 
* find the root cause here
* fix the test 
* add a simple test that just uses hashes and length in metafiles without any fancy attacks

**Comment by jku** [comment]
> find the root cause here

oh, it's likely the combination of:
* RepositorySimulator signing at request time
* using ecdsa keys that are not "deterministic"

the hashes/length  are over the whole file so include signatures.

**Comment by jku** [comment]
I filed an issue for switching the signing keytype (or otherwise solving the underlying issue).

That said, the test is still completely wrong: it claims to test a targets rollback but does not actually try to do one.

**Comment by AdamKorcz** [comment]
Should this remain open, @jku?

**Comment by jku** [comment]
yeah, that makes sense: currently client fails as expected but for wrong reasons.

Once #131 is implemented (and #130 is fixed) we have more confidence that the failure happens for right reason

**Comment by jku** [comment]
test_new_targets_hash_mismatch() is broken because of this as well: If any return values had been checked that would have been visible
