### ISSUE TITLE
refactor RepositorySimulator to sign explicitly

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#155]
_copying from in https://github.com/theupdateframework/tuf-conformance/issues/130#issuecomment-2290977900_

We probably should modify RepositorySimulator so that it signs metadata explicitly (and not magically at request time as it now does)

Potential design:           
* keep `mds` dictionary for storing the "current metadata working set"
* remove `signed_roots`, add `signed_mds: dict[str, list[bytes]]` where key is rolename
* remove `publish_root()` and `bump_root_by_one()`,  add something like `publish(role: str, bump_version: bool = True)` that bumps version if requested, makes a copy of roles current metadata from `mds`, signs it, adds bytes to signed_mds
* `fetch_metadata()` now looks up data only from `signed_mds` (and can return old versions)
* There's plenty of potential test changes, every test needs to be reviewed:
   * any test that modifies any targets role likely needs to `publish(role)` at least once
   * same for any tests that modify timestamp or snapshot without calling `update_*()` afterwards 
   * old metadata versions are now available from repository (this is more realistic so sounds good)
   * anything else?

**Comment by AdamKorcz** [comment]
Lgtm.

My additional thoughts below and thinking out loud regarding how I would approach this implementation-wise.

> remove signed_roots, add signed_mds: dict[str, list[bytes]] where key is rolename

sgtm. And we will look up the version in the same way we do now for root in `fetch_metadata`:

https://github.com/theupdateframework/tuf-conformance/blob/b8f2205151cf52499becade10fd9cddf574e6bf1/tuf_conformance/repository_simulator.py#L282-L285

### Signing process
I suppose this is part that we want to invoke manually:

https://github.com/theupdateframework/tuf-conformance/blob/b8f2205151cf52499becade10fd9cddf574e6bf1/tuf_conformance/repository_simulator.py#L288-L295

We should remove this part from `fetch_metadata` and generalise `publish_root` to allow us to specifically sign any role:

https://github.com/theupdateframework/tuf-conformance/blob/b8f2205151cf52499becade10fd9cddf574e6bf1/tuf_conformance/repository_simulator.py#L211-L219

I think that is the core of it.

From a test-writing perspective, I think we are covered to maintain a decent UX. The `publish` design _only_ takes care of signing based on existing signers/keys, and we need a good way to manage these before we publish. IMO we have good enough building blocks for that with `repo.add_key()`.

**Comment by jku** [comment]
Sounds good
* publish() probably should bump version (but maybe could have a argument for not bumping if there's a lot of need)
* if we want to break the repo in a very offensive way (let's say serve timestamp metadata when client requests snapshot) the test should just modify repo.mds directly
* if there are a lot of tests that want to do this, we can expose more complicated signing from RepositorySimulator (something like `sign(self, role: str, signers: list[Signer]) -> bytes` maybe that signs the current role with given keys and returns the serialized bytes that the caller can then insert wherever they want)

**Comment by jku** [comment]
> There's plenty of potential test changes, every test needs to be reviewed

* basically any and all metadata changes mean publishing is required
* this _may_ change the expected results: previously it was possible to modify v1 of any role and test that (since no publishing was required) but now we want 
   * RepositorySimulator._initialize() to publish v1 of all top level roles
   * the test to publish v2 for any changes it does
   
This looks like a purely manual review, there's not much we can do to automate.

**Comment by AdamKorcz** [comment]
Done in https://github.com/theupdateframework/tuf-conformance/pull/188
