### ISSUE TITLE
Release v2

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#201]
It's been five weeks since last release, should make a new one:
* current main has 12 new tests (with one or two still in flight)
* The change in "Expected failures" management is strictly speaking a breaking change: likely it will not actually break any actual users but I think we can still call this a 2.0.0 release
* Explicit publishing is a major internal change

Issues that could be considered for release:
* #199 is ready, needs review
* #182 would be nice but might not be ready in time
* with the explicit publish changes #29 would now make a lot of sense to sort out

**Comment by jku** [comment]
### Release notes draft

* BREAKING: `expected-failures` input was removed from the GitHub action: Use a `.xfail` file instead as described in README
* A dozen new tests were added

**Comment by segiddins** [comment]
Question regarding the xfail change -- how should clients handle a dynamic set of expected failures? Eg on ruby 3.0 we don't have ed25519 support, but do on 3.1+

**Comment by jku** [comment]
> Question regarding the xfail change -- how should clients handle a dynamic set of expected failures? Eg on ruby 3.0 we don't have ed25519 support, but do on 3.1+

Oh that's a good point. I suppose we could still have a optional input to select a different xfail file -- would that be reasonable?

**Comment by jku** [comment]
I suppose alternatively you could just modify/copy the file between invocations of the action but that would make your workflow a bit of a hack...

**Comment by jku** [comment]
Thinking this through: 
* If we add a new option for specifying the xfail file, it will be a little annoying to use in a GH action matrix -- since now you must provide the xfail file for every variant (even if most should just use the default)
* the second option (copying the xfail file before running the action) actually seems more reasonable since you could have the default file and then custom ones for just the special variants that need them:
    ```
          - name: Choose custom xfail file (if one exists)
            run: |
            XFAIL_FILE="${{ github.workspace }}/bin/tuf-conformance-entrypoint.xfail"
            cp -v "$XFAIL_FILE-${{ matrix.ruby }}" $XFAIL_FILE || true
    ```

@segiddins does that seem reasonable or do you have better ideas?

**Comment by jku** [comment]
I'm planning to do a v2.0.0 release today with current setup -- with the assumption that the xfail setup proposed in previous comment works. If it does not, we'll add an input or whatever is needed and make a 2.1 release
