### ISSUE TITLE
Output CLI command on failed test invocation

### ISSUE THREAD

**Issue by loosebazooka** [theupdateframework/tuf-conformance#229]
This is helpful at integration time when the CLI parser is failing because of nuances in parameter parsing.

Might also be helpful for test recreation locally.

**Comment by jku** [comment]
I'm a little worried about spamming the log but feels like worth a try.

ClientRunner could output the command during ClientRunner._run() but would have to always do it:
* ClientRunner has no way of differentiating expected failure from unexpected failure (we could change that with a refactor)
* ClientRunner has no way of differentiating parser failure from other unexpected failure (this would require CLI API change)

**Comment by jku** [comment]
Actually the easiest way to implement this is in the actual CLI implementation:
* the CLI is free to output what it wants: printing the full CLI args on startup is just fine, this is what at least go-tuf CLI does
* The test suite will only show this output if the test fails

I think it makes sense to print quite liberally in the CLI (or to set verbosity fairly high when calling the CLI): it'll be easier to debug, both when running manually and when a test fails in the test suite.

**Comment by loosebazooka** [comment]
Yeah that's what I ended up doing. Having the cli be verbose.
