### ISSUE TITLE
Output diff or expected/actual?

### ISSUE THREAD

**Issue by loosebazooka** [theupdateframework/tuf-conformance#230]
https://github.com/theupdateframework/tuf-conformance/blob/main/tuf_conformance/client_runner.py#L142 is a somewhat difficult error message to act on.

A more helpful failure might be output expected vs actual. We know metadata is serialized as a string in these tests. If it's too much to output to the screen then write it to a results file and upload it as an asset on the job? or like a deepdiff or something?

**Comment by jku** [comment]
Hmm, there might be two issues here:
* first, for some reason pytests verbose asserts don't seem to happen here fro some reason... They really should. Maybe asserting outside of the actual test function (like here in ClientRunner) is handled differently?
* second, maybe we should compare serialized bytes so pytest asserts are more helpful

**Comment by jku** [comment]
Aha:

> asserts in supporting modules which are not themselves test modules will not be rewritten.
> 
> You can manually enable assertion rewriting for an imported module by calling register_assert_rewrite before you 
> import it (a good place to do that is in your root conftest.py).

**Comment by jku** [comment]
>  If it's too much to output to the screen then write it to a results file and upload it as an asset on the job

I can increase default verbosity or make verbosity configurable if that's still needed, please file a new issue if current setup is not useful yet

**Comment by loosebazooka** [comment]
I think this doesn't matter much, now that I figured out the local experience, which is sufficient to debug the problem for me.
