### ISSUE TITLE
differentiate between infra errors and actual errors

### ISSUE THREAD

**Issue by loosebazooka** [theupdateframework/tuf-conformance#234]
tests in test_expiration require the existence of "faketime" on the system. Perhaps failures on missing infrastructure pieces can be surfaced differently?

**Comment by loosebazooka** [comment]
I think my "make dev" succeeded without FaceTime. Happy if it fails there

**Comment by jku** [comment]
oh right, it probably only fail when running the included clients (`make test-go-tuf`) : this is not helpful in your case.

So options would be 
* `make dev` should fail without faketime
* pytest refuses to run if faketime is missing
* individual tests refuse to run if faketime is missing

**Comment by loosebazooka** [comment]
This might matter a lot less when we're conformant. But getting started is confusing if it errors like this.
