### ISSUE TITLE
Consider github action

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#35]
sigstore-conformance provides a GitHub action that client projects can use. A similar setup might work for us: this would also mean we don't necessarily need to setup pypi releases etc...

This is not needed right now but at some point.

**Comment by jku** [comment]
> This is not needed right now but at some point

After discussing with Lukas: maybe this is actually a priority...
* if we add an action now, we pretty much have a MVP that we can show to client projects
* we can even add a workflow to python-tuf as an example

As long as we make it clear that the "client wrapper definition" is not stable yet this should be fine

**Comment by jku** [comment]
I've implemented an initial version. Further plans:
* Move a client wrapper and workflow to an external repo to test end-to-end and to have demonstration -- I think I'll add this to python-tuf (but I'll leave the test trigger to manual dispatch only so we can keep breaking things in tuf-conformance if needed)
* Add support for things like expected failures: #43
* Polish the output and debugging information #32
  * maybe upload an artifact for each failing test with the repository metadata and client output?

**Comment by AdamKorcz** [comment]
I suggest we add some basic documentation on adopting the GH action.

**Comment by jku** [comment]
I think everything here has been acted on or individual tickets have been filed
