### ISSUE TITLE
tests: add key rotation/update tests

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#38]
We should have tests for various key rotation cases: root is especially interesting and complicated but delegated roles sohuld be tested too.

python-tuf tests are pretty good so we can copy from there -- admittedly they are a little complicated because of the way they are parametrized: I wouldn't object if someone comes up with a simpler approach
* `test_updater_key_rotations.py` contains basic rotation tests
* there are special case tests for the fast forward recovery that happens during key rotation: search for `fast_forward_recovery` in test_updater_top_level_update.py

**Comment by AdamKorcz** [comment]
The `fast_forward_recovery` tests from python-tufs `test_updater_top_level_update.py` should all be in the conformance suite.

**Comment by jku** [comment]
I think this might be handled ok now -- certainly more cases could be added but the setup is there (parametrized tests where we can add more cases fairly easily) and a basic set of cases does exist.
