### ISSUE TITLE
separate self tests from actual test suite?

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#39]
Currently the "self tests" (tests that verify the test suite components work correctly)  and actual conformance tests are in the same directory and they all get executed at once
* this is probably incorrect: we should have separate runs for test suite and and "self tests" (currently test_repository_simulator.py) 
* it's also confusing for someone trying to find the actual conformance tests

opinions @AdamKorcz ?

**Comment by AdamKorcz** [comment]
I think we should have

1. a `make` rule that runs all test
2. a `make` rule that runs only conformance tests
3. a `make` rule that runs only "self tests"

IMO #3 should run in the CI of the conformance test suite.
