### ISSUE TITLE
Initial 1.0 release

### ISSUE THREAD

**Issue by jku** [theupdateframework/tuf-conformance#62]
meta issue for tracking what needs to be done before an initial release

infra:
* #61 
* #43
* #93
* #94
* #95
* #106

tests:
* at least review current set of tests

**Comment by jku** [comment]
From my POV after #95 we can tag v1 and publish this on GitHub Marketplace: then we can advertize on tuf channels and ask clients to start using the action

checklist for releasing:
* update the example in README to use the v1.0.0 tag or hash

**Comment by jku** [comment]
> ... publish this on GitHub Marketplace

actually this is not possible as _theupdateframework organization must accept the GitHub Marketplace Developer Agreement. Contact an org admin to accept it_. I think we don't really need to be on Marketplace :)

**Comment by AdamKorcz** [comment]
We should remove all print statements before the release.
